import Prism from "prismjs"
import "prismjs/components/prism-applescript"
import "prismjs/components/prism-asciidoc"
import "prismjs/components/prism-bash"
import "prismjs/components/prism-c"
import "prismjs/components/prism-cmake"
import "prismjs/components/prism-coffeescript"
import "prismjs/components/prism-cpp"
import "prismjs/components/prism-csharp"
import "prismjs/components/prism-css-extras"
import "prismjs/components/prism-dart"
import "prismjs/components/prism-django"
import "prismjs/components/prism-docker"
import "prismjs/components/prism-elixir"
import "prismjs/components/prism-erb"
import "prismjs/components/prism-erlang"
import "prismjs/components/prism-excel-formula"
import "prismjs/components/prism-go"
import "prismjs/components/prism-handlebars"
import "prismjs/components/prism-haskell"
import "prismjs/components/prism-http"
import "prismjs/components/prism-java"
import "prismjs/components/prism-javascript"
import "prismjs/components/prism-json"
import "prismjs/components/prism-kotlin"
import "prismjs/components/prism-lua"
import "prismjs/components/prism-makefile"
import "prismjs/components/prism-markdown"
import "prismjs/components/prism-markup"
import "prismjs/components/prism-nginx"
import "prismjs/components/prism-objectivec"
import "prismjs/components/prism-perl"
import "prismjs/components/prism-php-extras"
import "prismjs/components/prism-powershell"
import "prismjs/components/prism-python"
import "prismjs/components/prism-r"
import "prismjs/components/prism-ruby"
import "prismjs/components/prism-rust"
import "prismjs/components/prism-scala"
import "prismjs/components/prism-scss"
import "prismjs/components/prism-sql"
import "prismjs/components/prism-swift"
import "prismjs/components/prism-typescript"
import "prismjs/components/prism-vim"
import "prismjs/components/prism-xml-doc"
import "prismjs/components/prism-yaml"

export const list: {[key: string]: string} = {
  applescript: "applescript",
  asciidoc: "asciidoc",
  bash: "bash",
  c: "c",
  cmake: "cmake",
  coffeescript: "coffeescript",
  cpp: "cpp",
  csharp: "csharp",
  css: "css-extras",
  dart: "dart",
  django: "django",
  docker: "docker",
  elixir: "elixir",
  erb: "erb",
  erlang: "erlang",
  excel: "excel-formula",
  go: "go",
  handlebars: "handlebars",
  haskell: "haskell",
  http: "http",
  html: "html",
  markup: "markup",
  java: "java",
  javascript: "javascript",
  json: "json",
  kotlin: "kotlin",
  lua: "lua",
  makefile: "makefile",
  markdown: "markdown",
  nginx: "nginx",
  objectivec: "objectivec",
  perl: "perl",
  php: "php-extras",
  plain: "plain",
  powershell: "powershell",
  python: "python",
  r: "r",
  ruby: "ruby",
  rust: "rust",
  scala: "scala",
  scss: "scss",
  sql: "sql",
  swift: "swift",
  typescript: "typescript",
  vim: "vim",
  xml: "xml-doc",
  yaml: "yaml",
}

export default Prism
